In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd

csv_data = pd.read_csv('Regression.csv')

npArray = csv_data.to_numpy()

npArray

array([[ -5.        ,  -8.20141482],
       [ -4.98998999,  -8.73276922],
       [ -4.97997998, -13.35357674],
       ...,
       [  4.97997998,  15.77015417],
       [  4.98998999,  15.62292135],
       [  5.        ,  16.37365279]])

In [5]:
dataset = torch.from_numpy(npArray)

dataset

tensor([[ -5.0000,  -8.2014],
        [ -4.9900,  -8.7328],
        [ -4.9800, -13.3536],
        ...,
        [  4.9800,  15.7702],
        [  4.9900,  15.6229],
        [  5.0000,  16.3737]], dtype=torch.float64)

In [6]:
dataset_x = dataset[:,0:1]
dataset_y = dataset[:,1:]

In [7]:
dataset_x

tensor([[-5.0000],
        [-4.9900],
        [-4.9800],
        [-4.9700],
        [-4.9600],
        [-4.9499],
        [-4.9399],
        [-4.9299],
        [-4.9199],
        [-4.9099],
        [-4.8999],
        [-4.8899],
        [-4.8799],
        [-4.8699],
        [-4.8599],
        [-4.8498],
        [-4.8398],
        [-4.8298],
        [-4.8198],
        [-4.8098],
        [-4.7998],
        [-4.7898],
        [-4.7798],
        [-4.7698],
        [-4.7598],
        [-4.7497],
        [-4.7397],
        [-4.7297],
        [-4.7197],
        [-4.7097],
        [-4.6997],
        [-4.6897],
        [-4.6797],
        [-4.6697],
        [-4.6597],
        [-4.6496],
        [-4.6396],
        [-4.6296],
        [-4.6196],
        [-4.6096],
        [-4.5996],
        [-4.5896],
        [-4.5796],
        [-4.5696],
        [-4.5596],
        [-4.5495],
        [-4.5395],
        [-4.5295],
        [-4.5195],
        [-4.5095],
        [-4.4995],
        [-4.4895],
        [-4.

In [8]:
dataset_y

tensor([[-8.2014e+00],
        [-8.7328e+00],
        [-1.3354e+01],
        [-1.2104e+01],
        [-8.5620e+00],
        [-1.0834e+01],
        [-1.3910e+01],
        [-1.0527e+01],
        [-9.3266e+00],
        [-6.5656e+00],
        [-1.1836e+01],
        [-1.1398e+01],
        [-1.3320e+01],
        [-1.0977e+01],
        [-1.0964e+01],
        [-1.2673e+01],
        [-7.7643e+00],
        [-8.9588e+00],
        [-1.0766e+01],
        [-8.5731e+00],
        [-1.0461e+01],
        [-1.3542e+01],
        [-1.5970e+01],
        [-8.1459e+00],
        [-1.0224e+01],
        [-8.9831e+00],
        [-1.1397e+01],
        [-8.9646e+00],
        [-8.0237e+00],
        [-1.2822e+01],
        [-3.4170e+00],
        [-1.1100e+01],
        [-4.5178e+00],
        [-7.9162e+00],
        [-8.5752e+00],
        [-7.3996e+00],
        [-1.0982e+01],
        [-7.5675e+00],
        [-8.0377e+00],
        [-1.6341e+01],
        [-1.0414e+01],
        [-5.9091e+00],
        [-1.0261e+01],
        [-6

In [9]:
W = torch.rand(1,requires_grad=True)
b = torch.rand(1,requires_grad=True)

In [10]:
optimizer = optim.SGD([W,b],lr=0.01)

In [12]:
epochs = 2000

for epoch in range(epochs):
    
    epoch_Y = dataset_x * W + b

    #loss function
    cost = torch.mean((epoch_Y - dataset_y) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.6f}, b: {:.6f} Cost: {:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  100/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  200/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  300/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  400/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  500/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  600/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  700/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  800/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch  900/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1000/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1100/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1200/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1300/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1400/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1500/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1600/2000 W: 2.680616, b: 2.689500 Cost: 2.980555
Epoch 1700/2000 W: 2.680616, b: 2.689500 Cost: 2